[supervisord]
nodaemon=true
user=root

[program:Xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1920x1080x24
autostart=true
autorestart=true
priority=10

[program:tigervnc]
command=/usr/bin/vncserver :99 -localhost no -waitforjpeg 0
autostart=true
autorestart=true
priority=20

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 6080
autostart=true
autorestart=true
priority=30